# Generated by Django 3.2.7 on 2021-09-24 19:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo_profile')),
                ('nom', models.CharField(max_length=100, verbose_name='nom de famille')),
                ('prenom', models.CharField(max_length=50, verbose_name='votre prenom')),
                ('date', models.DateField(verbose_name='date de naissance')),
                ('lieu', models.CharField(max_length=100, verbose_name='lieu de naissance')),
                ('email', models.EmailField(max_length=254, verbose_name='votre email')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='contacte')),
            ],
        ),
    ]
